// The SQL database that we can run queries on
import pool from "./db.mjs";

// PORT=[port here] bun run server.js
const PORT = Bun.env.PORT ?? 3000;

// TODO: make an API to get data from the DB
// TODO: make some forms for the project manager page
// TODO: take these forms and insert/retrieve data from the db
// TODO: do something with these forms
// TODO: um idk

Bun.serve({
    // Listen on all interfaces
    hostname: "0.0.0.0",
    port: PORT,

    async fetch(req) {
        // The path of each request is locked to within the public folder.
        // Navigating to the root path / will access index.html by default.
        const url = new URL(req.url);

        // Serve static files
        const path = url.pathname === "/" ? "/index.html" : url.pathname;

        // The client is sending data to the server
        if (req.method === "POST") {
            const form_data = await req.formData();
            for (const [key, value] of form_data.entries()) {
                console.log(JSON.stringify({ key, value }));
            }

            return new Response("YOU DARE SEND DATA TO ME!?!?");
        }

        // The client is requesting data from the server
        if (req.method === "GET") {
            // If the file exists, serve that file - this also handles the
            // autogenerated posts based on user submissions (as they are
            // created when a user submits something).
            const file = Bun.file(`./public${path}`);
            if (await file.exists()) return new Response(file);

            // API endpoints for fetching data from each SQL table
            try {
                const table_list = [
                    "users", // accessible at /api/users
                    "project", // accessible at /api/project
                    "category_tags", // accessible at /api/category_tags
                    "project_tags", // accessible at /api/project_tags
                    "project_members", // accessible at /api/project_members
                ];

                for (const table of table_list) {
                    if (url.pathname === `/api/${table}`) {
                        const query = `SELECT * FROM ${table};`;
                        const result = await pool.query(query);
                        const json_data = JSON.stringify(result.rows);
                        return new Response(json_data);
                    }
                }
            } catch (err) {
                console.log(`Error encountered: ${err}`);
                return new Response(JSON.stringify(err), { status: 500 });
            }

            // If nothing above handled the request, send a 404 response
            return new Response("404 not found.", { status: 404 });
        }
    },
});

// We can access the website at this address:
console.log(`Server running at http://0.0.0.0:${PORT}`);
