// The SQL database that we can run queries on
import { apiPost, apiGet } from "./api.js";

// PORT=[port here] bun run server.js
const PORT = Bun.env.PORT ?? 3000;

// TODO: do something with these forms
// TODO: um idk

Bun.serve({
    // Listen on all interfaces
    hostname: "0.0.0.0",
    port: PORT,

    async fetch(req) {
        // The path of each request is locked to within the public folder.
        // Navigating to the root path / will access index.html by default.
        const url = new URL(req.url);

        // Serve static files
        const path = url.pathname === "/" ? "/index.html" : url.pathname;

        // ------------------------------------------- HANDLE DATA MODIFICATION
        if (req.method === "POST") {
            const form_data = await req.formData();

            try {
                const api_response = await apiPost(url, form_data);
                if (api_response) return api_response;
            } catch (err) {
                // Just in case we have out-of-band errors, like for SQL
                console.log(`POST error encountered: ${err} --- FORM DATA:`);
                // Log the offending form data for debugging
                for (const [key, value] of form_data.entries())
                    console.log(JSON.stringify({ key, value }));
                return Response.json(err, { status: 500 });
            }
        }

        // ----------------------------------------------- HANDLE DATA FETCHING
        if (req.method === "GET") {
            try {
                // If the file exists, serve that file - this also handles the
                // autogenerated posts based on user submissions (as they are
                // created when a user submits something).
                const file = Bun.file(`./public${path}`);
                if (await file.exists()) return new Response(file);

                // API endpoints for fetching data from each SQL table
                const api_response = await apiGet(url);
                if (api_response) return api_response;
            } catch (err) {
                // Just in case we have out-of-band errors, like for SQL
                console.log(`GET error encountered: ${err}`);
                return Response.json(err, { status: 500 });
            }
        }

        // If nothing above handled the request, send a 404 response
        return new Response("404 not found.", { status: 404 });
    },
});

// We can access the website at this address:
console.log(`Server running at http://0.0.0.0:${PORT}`);
