-- SERVER: "psql -U retrodev -d coco -f tables.sql" to reset the DB
-- Drop tables in reverse dependency order to avoid foreign key conflicts
DROP TABLE IF EXISTS public.project_members CASCADE;

DROP TABLE IF EXISTS public.projects_tags CASCADE;

DROP TABLE IF EXISTS public.category_tags CASCADE;

DROP TABLE IF EXISTS public.project CASCADE;

DROP TABLE IF EXISTS public.users CASCADE;

-- Users table
CREATE TABLE
  public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    pw_salt BYTEA NOT NULL,
    pw_hash BYTEA NOT NULL,
    email TEXT NOT NULL,
    phone_number TEXT,
    other_link TEXT,
    created_at TIMESTAMP
    WITH
      TIME ZONE NOT NULL DEFAULT NOW ()
  ) TABLESPACE pg_default;

-- Project table
CREATE TABLE
  public.project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name TEXT NOT NULL,
    max_people INTEGER NOT NULL,
    details TEXT NOT NULL,
    created_at TIMESTAMP
    WITH
      TIME ZONE NOT NULL DEFAULT NOW ()
  ) TABLESPACE pg_default;

-- Category_tags table
CREATE TABLE
  public.category_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP
    WITH
      TIME ZONE NOT NULL DEFAULT NOW ()
  ) TABLESPACE pg_default;

-- Projects_tags table (many-to-many: project <-> category_tags)
CREATE TABLE
  public.projects_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP
    WITH
      TIME ZONE NOT NULL DEFAULT NOW (),
      project_id BIGINT NOT NULL REFERENCES public.project (id) ON UPDATE CASCADE ON DELETE CASCADE,
      tag_id BIGINT NOT NULL REFERENCES public.category_tags (id) ON UPDATE CASCADE ON DELETE CASCADE
  ) TABLESPACE pg_default;

-- Project_members table (many-to-many: users <-> project)
CREATE TABLE
  public.project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP
    WITH
      TIME ZONE NOT NULL DEFAULT NOW (),
      role VARCHAR NOT NULL,
      user_id BIGINT NOT NULL REFERENCES public.users (id) ON UPDATE CASCADE ON DELETE CASCADE,
      project_id BIGINT NOT NULL REFERENCES public.project (id) ON UPDATE CASCADE ON DELETE CASCADE
  ) TABLESPACE pg_default;
