-- Users table
create table
  public.users (
    id bigint generated by default as identity not null,
    user_name text not null,
    -- The salt is appended to the password before it is hashed
    pw_salt char(16) not null,
    -- The password hash is sha2-256, for authenticating a user
    pw_hash binary(32) not null,
    email text not null,
    phone_number text null,
    other_link text null,
    created_at timestamp
    with
      time zone not null default now (),
      constraint user_pkey primary key (id)
  ) TABLESPACE pg_default;

-- Project
create table
  public.project (
    id bigint generated by default as identity not null,
    project_name text not null,
    max_people integer not null,
    details text not null,
    created_at timestamp
    with
      time zone not null default now (),
      constraint project_pkey primary key (id)
  ) TABLESPACE pg_default;

-- Category_tags
create table
  public.category_tags (
    id bigint generated by default as identity not null,
    name text not null,
    created_at timestamp
    with
      time zone not null default now (),
      constraint project_tags_pkey primary key (id),
      constraint project_tags_name_key unique (name)
  ) TABLESPACE pg_default;

-- Projects_tags
create table
  public.projects_tags (
    id bigint generated by default as identity not null,
    created_at timestamp
    with
      time zone not null default now (),
      project_id bigint not null,
      tag_id bigint not null,
      constraint projects_tags_pkey primary key (id),
      constraint projects_tags_project_id_fkey foreign KEY (project_id) references project (id) on update CASCADE on delete CASCADE,
      constraint projects_tags_tag_id_fkey foreign KEY (tag_id) references category_tags (id) on update CASCADE on delete CASCADE
  ) TABLESPACE pg_default;

-- Project_members
create table
  public.project_members (
    id bigint generated by default as identity not null,
    created_at timestamp
    with
      time zone not null default now (),
      role character varying not null,
      user_id bigint not null,
      project_id bigint not null,
      constraint project_members_pkey primary key (id),
      constraint project_members_project_id_fkey foreign KEY (project_id) references project (id) on update CASCADE on delete CASCADE,
      constraint project_members_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
  ) TABLESPACE pg_default;